In [1]:
# !pip install sympy

In [2]:
import numpy as np

In [3]:
from sympy import *
init_printing(use_unicode=True)

### Numpy? 

In [4]:
A = np.random.rand(3, 3)
b = np.random.rand(3, 1)
A, b, np.linalg.inv(A) @ b

(array([[0.89459304, 0.35219112, 0.8320374 ],
        [0.11395178, 0.49933429, 0.25035773],
        [0.28569373, 0.47733318, 0.69070499]]),
 array([[0.98353869],
        [0.43350057],
        [0.94394047]]),
 array([[-0.16352885],
        [ 0.28516338],
        [ 1.23720213]]))

### Sympy - Getting RREF form

In [5]:
M1 = Matrix([[10, 8, 3, 1], 
            [8, 8, 2, 2]])
M1, M1.rref()

⎛⎡10  8  3  1⎤  ⎛⎡1  0  1/2   -1/2⎤        ⎞⎞
⎜⎢           ⎥, ⎜⎢                ⎥, (0, 1)⎟⎟
⎝⎣8   8  2  2⎦  ⎝⎣0  1  -1/4  3/4 ⎦        ⎠⎠

#### Finding rank of a matrix

In [6]:
M1.rank()

2

### Inverse of matrix using Gaussian elimination

Confirmation that right side of augmented matrix is inverse, [A | I] => [I | A^-1]

In [7]:
M2 = Matrix([[10, 8, 1, 0], 
            [8, 8, 0, 1]])
M2, M2.rref()

⎛⎡10  8  1  0⎤  ⎛⎡1  0  1/2   -1/2⎤        ⎞⎞
⎜⎢           ⎥, ⎜⎢                ⎥, (0, 1)⎟⎟
⎝⎣8   8  0  1⎦  ⎝⎣0  1  -1/2  5/8 ⎦        ⎠⎠

In [8]:
M3 = Matrix([[10, 8], 
            [8, 8]])
M3, M3.inv()

⎛⎡10  8⎤  ⎡1/2   -1/2⎤⎞
⎜⎢     ⎥, ⎢          ⎥⎟
⎝⎣8   8⎦  ⎣-1/2  5/8 ⎦⎠

### Norm of a vector

In [9]:
M4 = Matrix([[2], [3], [5]])
M4, M4.norm() # Frobenius norm / Euclidean norm / L2 norm

⎛⎡2⎤     ⎞
⎜⎢ ⎥     ⎟
⎜⎢3⎥, √38⎟
⎜⎢ ⎥     ⎟
⎝⎣5⎦     ⎠

In [10]:
M5 = Matrix([2, 3, 5])
M5, M5.norm() # Frobenius norm / Euclidean norm / L2 norm

⎛⎡2⎤     ⎞
⎜⎢ ⎥     ⎟
⎜⎢3⎥, √38⎟
⎜⎢ ⎥     ⎟
⎝⎣5⎦     ⎠

In [11]:
### Dot product (dot product for A=I)
M6 = Matrix([1, 2, 3])
M7 = Matrix([1, 1, 1])
M6, M7, M6.dot(M7)

⎛⎡1⎤  ⎡1⎤   ⎞
⎜⎢ ⎥  ⎢ ⎥   ⎟
⎜⎢2⎥, ⎢1⎥, 6⎟
⎜⎢ ⎥  ⎢ ⎥   ⎟
⎝⎣3⎦  ⎣1⎦   ⎠

### Gram-Schmidt orthogonalization

In [12]:
M8 = [Matrix([3, 2]), Matrix([1,2])]
M8, GramSchmidt(M8), GramSchmidt(M8, True)

⎛                            ⎡⎡3⋅√13⎤  ⎡-2⋅√13 ⎤⎤⎞
⎜            ⎡     ⎡-8/13⎤⎤  ⎢⎢─────⎥  ⎢───────⎥⎥⎟
⎜⎡⎡3⎤  ⎡1⎤⎤  ⎢⎡3⎤  ⎢     ⎥⎥  ⎢⎢  13 ⎥  ⎢   13  ⎥⎥⎟
⎜⎢⎢ ⎥, ⎢ ⎥⎥, ⎢⎢ ⎥, ⎢ 12  ⎥⎥, ⎢⎢     ⎥, ⎢       ⎥⎥⎟
⎜⎣⎣2⎦  ⎣2⎦⎦  ⎢⎣2⎦  ⎢ ──  ⎥⎥  ⎢⎢2⋅√13⎥  ⎢ 3⋅√13 ⎥⎥⎟
⎜            ⎣     ⎣ 13  ⎦⎦  ⎢⎢─────⎥  ⎢ ───── ⎥⎥⎟
⎝                            ⎣⎣  13 ⎦  ⎣   13  ⎦⎦⎠

### Determinant

In [13]:
M9 = Matrix([[1, 1, 3], [3, 4, 5], [5, 3, 4]])
M9, M9.det()

⎛⎡1  1  3⎤     ⎞
⎜⎢       ⎥     ⎟
⎜⎢3  4  5⎥, -19⎟
⎜⎢       ⎥     ⎟
⎝⎣5  3  4⎦     ⎠

### Trace

In [14]:
M9, M9.trace() # sum of diagonals

⎛⎡1  1  3⎤   ⎞
⎜⎢       ⎥   ⎟
⎜⎢3  4  5⎥, 9⎟
⎜⎢       ⎥   ⎟
⎝⎣5  3  4⎦   ⎠

### Minor and cofactor, adjugate

In [15]:
M9.minor_submatrix(0, 0), M9.minor(0, 0), M9.cofactor(0, 0) # 1st row and 1st column

⎛⎡4  5⎤      ⎞
⎜⎢    ⎥, 1, 1⎟
⎝⎣3  4⎦      ⎠

In [16]:
M9.minor_submatrix(0, 1), M9.minor(0, 1), M9.cofactor(0, 1) # 1st row and 2nd column

⎛⎡3  5⎤         ⎞
⎜⎢    ⎥, -13, 13⎟
⎝⎣5  4⎦         ⎠

In [17]:
M9.minor_submatrix(0, 2), M9.minor(0, 2), M9.cofactor(0, 2) # 1st row and 3rd column

⎛⎡3  4⎤          ⎞
⎜⎢    ⎥, -11, -11⎟
⎝⎣5  3⎦          ⎠

In [18]:
M9.cofactor_matrix(), M9.adjugate() # adjugate matrix is the transpose of cofactor matrix

⎛⎡1   13   -11⎤  ⎡ 1    5   -7⎤⎞
⎜⎢            ⎥  ⎢            ⎥⎟
⎜⎢5   -11   2 ⎥, ⎢13   -11  4 ⎥⎟
⎜⎢            ⎥  ⎢            ⎥⎟
⎝⎣-7   4    1 ⎦  ⎣-11   2   1 ⎦⎠

#### Inverse by adjugate / determinant method

In [19]:
M9.adjugate() / M9.det()

⎡-1/19  -5/19  7/19 ⎤
⎢                   ⎥
⎢-13     11         ⎥
⎢────    ──    -4/19⎥
⎢ 19     19         ⎥
⎢                   ⎥
⎢ 11                ⎥
⎢ ──    -2/19  -1/19⎥
⎣ 19                ⎦

In [20]:
M9.inv() # same value as above

⎡-1/19  -5/19  7/19 ⎤
⎢                   ⎥
⎢-13     11         ⎥
⎢────    ──    -4/19⎥
⎢ 19     19         ⎥
⎢                   ⎥
⎢ 11                ⎥
⎢ ──    -2/19  -1/19⎥
⎣ 19                ⎦

### Charecteristic polynomial

In [21]:
from sympy import Matrix
from sympy.abc import x, y
M9, M9.charpoly().as_expr()

⎛⎡1  1  3⎤                      ⎞
⎜⎢       ⎥   3      2           ⎟
⎜⎢3  4  5⎥, λ  - 9⋅λ  - 9⋅λ + 19⎟
⎜⎢       ⎥                      ⎟
⎝⎣5  3  4⎦                      ⎠

In [22]:
M10 = Matrix([[2, 3], [5, 6]])
M10, M10.charpoly().as_expr()

⎛⎡2  3⎤   2          ⎞
⎜⎢    ⎥, λ  - 8⋅λ - 3⎟
⎝⎣5  6⎦              ⎠

In [23]:
solve(M10.charpoly().as_expr()) # finding roots of charecteristic equation

[4 - √19, 4 + √19]

### Eigenvalues and eigenvectors

In [24]:
M10, M10.eigenvals(multiple=True)

⎛⎡2  3⎤                    ⎞
⎜⎢    ⎥, [4 + √19, 4 - √19]⎟
⎝⎣5  6⎦                    ⎠

In [25]:
M10.eigenvects(), # [(eigenval, multiplicity, eigenspace), …]

⎛⎡⎛            ⎡⎡  √19   2⎤⎤⎞  ⎛            ⎡⎡  2   √19⎤⎤⎞⎤ ⎞
⎜⎢⎜            ⎢⎢- ─── - ─⎥⎥⎟  ⎜            ⎢⎢- ─ + ───⎥⎥⎟⎥ ⎟
⎜⎢⎜4 - √19, 1, ⎢⎢   5    5⎥⎥⎟, ⎜4 + √19, 1, ⎢⎢  5    5 ⎥⎥⎟⎥,⎟
⎜⎢⎜            ⎢⎢         ⎥⎥⎟  ⎜            ⎢⎢         ⎥⎥⎟⎥ ⎟
⎝⎣⎝            ⎣⎣    1    ⎦⎦⎠  ⎝            ⎣⎣    1    ⎦⎦⎠⎦ ⎠

## You can also do stuff with symbols in the matrices

#### Generic expression for eigenvalues of 2x2 matrix

In [26]:
x, a, b, c, d = symbols('x a b c d')
M11 = Matrix([[a, b], [c, d]])
M11, M11.charpoly().as_expr()

⎛⎡a  b⎤               2             ⎞
⎜⎢    ⎥, a⋅d - b⋅c + λ  + λ⋅(-a - d)⎟
⎝⎣c  d⎦                             ⎠

In [27]:
str(M11.charpoly().as_expr())

'a*d - b*c + lambda**2 + lambda*(-a - d)'

In [28]:
solve('a*d - b*c + x**2 + x*(-a - d)', symbols=['x'], exclude = ['a', 'b', 'c', 'd']) # solving for x

⎡           _________________________             _________________________⎤
⎢          ╱  2                    2             ╱  2                    2 ⎥
⎢a   d   ╲╱  a  - 2⋅a⋅d + 4⋅b⋅c + d    a   d   ╲╱  a  - 2⋅a⋅d + 4⋅b⋅c + d  ⎥
⎢─ + ─ - ────────────────────────────, ─ + ─ + ────────────────────────────⎥
⎣2   2                2                2   2                2              ⎦

### Solved problems from previous quizzes

#### Eigenvectors for ...

In [29]:
a = symbols('a')
M12 = Matrix([[0, 0, a], [0, 0, 0], [0, 0, 0]])
M12, M12.eigenvects()

⎛⎡0  0  a⎤  ⎡⎛      ⎡⎡1⎤  ⎡0⎤⎤⎞⎤⎞
⎜⎢       ⎥  ⎢⎜      ⎢⎢ ⎥  ⎢ ⎥⎥⎟⎥⎟
⎜⎢0  0  0⎥, ⎢⎜0, 3, ⎢⎢0⎥, ⎢1⎥⎥⎟⎥⎟
⎜⎢       ⎥  ⎢⎜      ⎢⎢ ⎥  ⎢ ⎥⎥⎟⎥⎟
⎝⎣0  0  0⎦  ⎣⎝      ⎣⎣0⎦  ⎣0⎦⎦⎠⎦⎠

#### Eigenvalues for ...

In [30]:
M13 = Matrix([[5, 3], [2, 9]])
M13, M13.eigenvals(multiple=True)

⎛⎡5  3⎤                    ⎞
⎜⎢    ⎥, [√10 + 7, 7 - √10]⎟
⎝⎣2  9⎦                    ⎠

#### Finding ...

In [31]:
M14 = Matrix([[3, 2], [1, 4]])
M14 * M14.adjugate()

⎡10  0 ⎤
⎢      ⎥
⎣0   10⎦

#### Trace of

In [32]:
M15 = Matrix([[1, 0, 4], [2, 0, 4], [3, 6, 9]])
M15, M15.trace()

⎛⎡1  0  4⎤    ⎞
⎜⎢       ⎥    ⎟
⎜⎢2  0  4⎥, 10⎟
⎜⎢       ⎥    ⎟
⎝⎣3  6  9⎦    ⎠

#### Eigenvectors for ...

In [33]:
x, a, k = symbols('x a k')
M16 = Matrix([[a, k-a], [k-a, a]])
M16, M16.eigenvals(multiple=True), M16.eigenvects()

⎛⎡  a     -a + k⎤                ⎡⎛      ⎡⎡1⎤⎤⎞  ⎛            ⎡⎡-1⎤⎤⎞⎤⎞
⎜⎢              ⎥, [k, 2⋅a - k], ⎢⎜k, 1, ⎢⎢ ⎥⎥⎟, ⎜2⋅a - k, 1, ⎢⎢  ⎥⎥⎟⎥⎟
⎝⎣-a + k    a   ⎦                ⎣⎝      ⎣⎣1⎦⎦⎠  ⎝            ⎣⎣1 ⎦⎦⎠⎦⎠

#### Value of a for det = 0

In [34]:
a = symbols('a')
M17 = Matrix([[2, 3, 5], [1, a, 2], [0, 1, -1]])
M17, M17.det()

⎛⎡2  3  5 ⎤         ⎞
⎜⎢        ⎥         ⎟
⎜⎢1  a  2 ⎥, 4 - 2⋅a⎟
⎜⎢        ⎥         ⎟
⎝⎣0  1  -1⎦         ⎠